import { QuoteFormData } from "@/components/quote-form/types";

export const sampleQuoteData: QuoteFormData = {
	creatorName: "John Smith",
	careHomeName: "Sample Care Home",
	numberOfDiningRooms: 2,
	totalResidents: 111,
	diningRooms: [
		{
			name: "Main Dining Room",
			mealCategories: [
				"Multi Twin",
				"Level 4",
				"Allergen Free",
				"Kosher",
				"Halal",
				"Caribbean",
			],
			multiTwinSize: "Large",
			multiTwinResidents: 40,
			level3Residents: 0,
			level4Residents: 5,
			level5Residents: 0,
			level6Residents: 5,
			allergyFreeResidents: 5,
			fingerFoodResidents: 0,
			miniMealResidents: 5,
			caribbeanDietsResidents: 5,
			halalDietsResidents: 20,
			kosherDietsResidents: 6,
			totalResidentsInDiningRoom: 91,
		},
		{
			name: "Special Care Dining",
			mealCategories: ["Level 3", "Level 5", "Finger Foods"],
			multiTwinResidents: 0,
			level3Residents: 12,
			level4Residents: 0,
			level5Residents: 98,
			level6Residents: 0,
			allergyFreeResidents: 0,
			fingerFoodResidents: 8,
			miniMealResidents: 0,
			caribbeanDietsResidents: 0,
			halalDietsResidents: 0,
			kosherDietsResidents: 0,
			totalResidentsInDiningRoom: 20,
		},
	],
	selectedMenu: { menuName: "Menu A - Jan 2025", menuId: "97481" },
	extras: {
		includeBreakfast: false,
		lighterMealOption: "standard",
		includeLighterMealDessert: false,
		level4Options: ["Breakfast", "Snacks"],
		level5Options: ["Dessert"],
		level6Options: [],
	},
	priceListName: {
		customerNo: "1103998",
		priceHierarchy: "0008801129",
		customerId: "2406",
		customerName: "National",
	},
	currentLabourHours: 40,
	currentLabourCost: 50000,
	currentFoodSpend: 75000,
	estimatedNonApetitoSpend: 25000,
	numberOfRoles: 3,
	roles: [
		{
			name: "Kitchen Manager",
			hourlyRate: 12,
			hoursPerWeek: 40,
			numberOfSimilarRoles: 1,
		},
		{
			name: "Chef",
			hourlyRate: 15,
			hoursPerWeek: 35,
			numberOfSimilarRoles: 2,
		},
		{
			name: "Kitchen Assistant",
			hourlyRate: 18,
			hoursPerWeek: 30,
			numberOfSimilarRoles: 3,
		},
	],
	apetitoLabor: {
		name: "Apetito Labor",
		hourlyRate: 14,
		hoursPerWeek: 35,
		numberOfSimilarRoles: 1,
	},
};
